SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 6 (class 2615 OID 16389)
-- Name: tickets; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA tickets;


ALTER SCHEMA tickets OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 16709)
-- Name: auth_user; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.auth_user (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    password_hash character varying(128),
    active boolean DEFAULT true NOT NULL,
    admin boolean DEFAULT false NOT NULL,
    image_path character varying(256),
    settings json,
    notifications json
);


ALTER TABLE tickets.auth_user OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16708)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16774)
-- Name: comment; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.comment (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    parent_comment_id integer,
    text text NOT NULL,
    created_time timestamp without time zone DEFAULT now() NOT NULL,
    modified_time timestamp without time zone
);


ALTER TABLE tickets.comment OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16773)
-- Name: comment_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 16798)
-- Name: label; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.label (
    id integer NOT NULL,
    team_id integer NOT NULL,
    name character varying(128) NOT NULL,
    "order" integer
);


ALTER TABLE tickets.label OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 16797)
-- Name: label_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.label ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.label_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 16839)
-- Name: password_reset; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.password_reset (
    id character varying(40) NOT NULL,
    auth_user_id integer NOT NULL,
    expiration_time timestamp without time zone NOT NULL
);


ALTER TABLE tickets.password_reset OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16750)
-- Name: priority; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.priority (
    id integer NOT NULL,
    team_id integer NOT NULL,
    name character varying(128) NOT NULL,
    "order" integer
);


ALTER TABLE tickets.priority OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 16749)
-- Name: priority_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.priority ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.priority_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 16817)
-- Name: queue; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.queue (
    id integer NOT NULL,
    config json NOT NULL
);


ALTER TABLE tickets.queue OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 16816)
-- Name: queue_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.queue ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.queue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 16834)
-- Name: session; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.session (
    id character varying(40) NOT NULL,
    user_id integer NOT NULL,
    expiration_time timestamp without time zone NOT NULL,
    renewal_time timestamp without time zone NOT NULL
);


ALTER TABLE tickets.session OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16744)
-- Name: status; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.status (
    id integer NOT NULL,
    team_id integer NOT NULL,
    name character varying(128) NOT NULL,
    "order" integer
);


ALTER TABLE tickets.status OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16743)
-- Name: status_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16728)
-- Name: team; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.team (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    description text
);


ALTER TABLE tickets.team OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 16829)
-- Name: team_has_queue; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.team_has_queue (
    team_id integer NOT NULL,
    queue_id integer NOT NULL
);


ALTER TABLE tickets.team_has_queue OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 16791)
-- Name: team_has_user; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.team_has_user (
    team_id integer NOT NULL,
    user_id integer NOT NULL,
    team_admin boolean DEFAULT true NOT NULL
);


ALTER TABLE tickets.team_has_user OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16727)
-- Name: team_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.team ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.team_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16756)
-- Name: ticket; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.ticket (
    id integer NOT NULL,
    title text NOT NULL,
    description text,
    status_id integer NOT NULL,
    assignee_user_id integer,
    created_time timestamp without time zone DEFAULT now() NOT NULL,
    created_by_user_id integer NOT NULL,
    modified_time timestamp without time zone DEFAULT now() NOT NULL,
    modified_by_user_id integer NOT NULL,
    customer_user_id integer,
    priority_id integer NOT NULL,
    ticket_type_id integer,
    notes text,
    type_data json
);


ALTER TABLE tickets.ticket OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 16765)
-- Name: ticket_for_user; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.ticket_for_user (
    user_id integer NOT NULL,
    ticket_id integer NOT NULL,
    watch boolean DEFAULT true,
    private_notes text
);


ALTER TABLE tickets.ticket_for_user OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 16803)
-- Name: ticket_has_label; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.ticket_has_label (
    ticket_id integer NOT NULL,
    label_id integer NOT NULL
);


ALTER TABLE tickets.ticket_has_label OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16755)
-- Name: ticket_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.ticket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.ticket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 16783)
-- Name: ticket_modification; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.ticket_modification (
    id integer NOT NULL,
    ticket_id integer NOT NULL,
    modified_by_user_id integer NOT NULL,
    modified_time timestamp without time zone DEFAULT now() NOT NULL,
    changes json NOT NULL
);


ALTER TABLE tickets.ticket_modification OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16782)
-- Name: ticket_modification_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.ticket_modification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.ticket_modification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16736)
-- Name: ticket_type; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.ticket_type (
    id integer NOT NULL,
    team_id integer NOT NULL,
    name character varying(128) NOT NULL,
    "order" integer,
    schema json
);


ALTER TABLE tickets.ticket_type OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16735)
-- Name: ticket_type_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.ticket_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.ticket_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16719)
-- Name: user; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets."user" (
    id integer NOT NULL,
    created_time timestamp without time zone DEFAULT now() NOT NULL,
    first_name character varying(128) NOT NULL,
    last_name character varying(128) NOT NULL,
    auth_user_id integer,
    custom_data json
);


ALTER TABLE tickets."user" OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 16809)
-- Name: user_custom_schema; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.user_custom_schema (
    id integer NOT NULL,
    schema json
);


ALTER TABLE tickets.user_custom_schema OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 16808)
-- Name: user_custom_schema_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets.user_custom_schema ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.user_custom_schema_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 16824)
-- Name: user_has_queue; Type: TABLE; Schema: tickets; Owner: postgres
--

CREATE TABLE tickets.user_has_queue (
    user_id integer NOT NULL,
    queue_id integer NOT NULL
);


ALTER TABLE tickets.user_has_queue OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16718)
-- Name: user_id_seq; Type: SEQUENCE; Schema: tickets; Owner: postgres
--

ALTER TABLE tickets."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME tickets.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5031 (class 0 OID 16709)
-- Dependencies: 219
-- Data for Name: auth_user; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.auth_user (id, email, password_hash, active, admin, image_path, settings, notifications) FROM stdin;
\.


--
-- TOC entry 5046 (class 0 OID 16774)
-- Dependencies: 234
-- Data for Name: comment; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.comment (id, ticket_id, parent_comment_id, text, created_time, modified_time) FROM stdin;
\.


--
-- TOC entry 5051 (class 0 OID 16798)
-- Dependencies: 239
-- Data for Name: label; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.label (id, team_id, name, "order") FROM stdin;
\.


--
-- TOC entry 5060 (class 0 OID 16839)
-- Dependencies: 248
-- Data for Name: password_reset; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.password_reset (id, auth_user_id, expiration_time) FROM stdin;
\.


--
-- TOC entry 5041 (class 0 OID 16750)
-- Dependencies: 229
-- Data for Name: priority; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.priority (id, team_id, name, "order") FROM stdin;
\.


--
-- TOC entry 5056 (class 0 OID 16817)
-- Dependencies: 244
-- Data for Name: queue; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.queue (id, config) FROM stdin;
\.


--
-- TOC entry 5059 (class 0 OID 16834)
-- Dependencies: 247
-- Data for Name: session; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.session (id, user_id, expiration_time, renewal_time) FROM stdin;
\.


--
-- TOC entry 5039 (class 0 OID 16744)
-- Dependencies: 227
-- Data for Name: status; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.status (id, team_id, name, "order") FROM stdin;
\.


--
-- TOC entry 5035 (class 0 OID 16728)
-- Dependencies: 223
-- Data for Name: team; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.team (id, name, description) FROM stdin;
\.


--
-- TOC entry 5058 (class 0 OID 16829)
-- Dependencies: 246
-- Data for Name: team_has_queue; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.team_has_queue (team_id, queue_id) FROM stdin;
\.


--
-- TOC entry 5049 (class 0 OID 16791)
-- Dependencies: 237
-- Data for Name: team_has_user; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.team_has_user (team_id, user_id, team_admin) FROM stdin;
\.


--
-- TOC entry 5043 (class 0 OID 16756)
-- Dependencies: 231
-- Data for Name: ticket; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.ticket (id, title, description, status_id, assignee_user_id, created_time, created_by_user_id, modified_time, modified_by_user_id, customer_user_id, priority_id, ticket_type_id, notes, type_data) FROM stdin;
\.


--
-- TOC entry 5044 (class 0 OID 16765)
-- Dependencies: 232
-- Data for Name: ticket_for_user; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.ticket_for_user (user_id, ticket_id, watch, private_notes) FROM stdin;
\.


--
-- TOC entry 5052 (class 0 OID 16803)
-- Dependencies: 240
-- Data for Name: ticket_has_label; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.ticket_has_label (ticket_id, label_id) FROM stdin;
\.


--
-- TOC entry 5048 (class 0 OID 16783)
-- Dependencies: 236
-- Data for Name: ticket_modification; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.ticket_modification (id, ticket_id, modified_by_user_id, modified_time, changes) FROM stdin;
\.


--
-- TOC entry 5037 (class 0 OID 16736)
-- Dependencies: 225
-- Data for Name: ticket_type; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.ticket_type (id, team_id, name, "order", schema) FROM stdin;
\.


--
-- TOC entry 5033 (class 0 OID 16719)
-- Dependencies: 221
-- Data for Name: user; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets."user" (id, created_time, first_name, last_name, auth_user_id, custom_data) FROM stdin;
1	2025-07-02 17:15:20.746281	John	Doe	\N	\N
\.


--
-- TOC entry 5054 (class 0 OID 16809)
-- Dependencies: 242
-- Data for Name: user_custom_schema; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.user_custom_schema (id, schema) FROM stdin;
\.


--
-- TOC entry 5057 (class 0 OID 16824)
-- Dependencies: 245
-- Data for Name: user_has_queue; Type: TABLE DATA; Schema: tickets; Owner: postgres
--

COPY tickets.user_has_queue (user_id, queue_id) FROM stdin;
\.


--
-- TOC entry 5085 (class 0 OID 0)
-- Dependencies: 218
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.auth_user_id_seq', 1, false);


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 233
-- Name: comment_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.comment_id_seq', 1, false);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 238
-- Name: label_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.label_id_seq', 1, false);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 228
-- Name: priority_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.priority_id_seq', 1, false);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 243
-- Name: queue_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.queue_id_seq', 1, false);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 226
-- Name: status_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.status_id_seq', 1, false);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 222
-- Name: team_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.team_id_seq', 1, false);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 230
-- Name: ticket_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.ticket_id_seq', 1, false);


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 235
-- Name: ticket_modification_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.ticket_modification_id_seq', 1, false);


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 224
-- Name: ticket_type_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.ticket_type_id_seq', 1, false);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 241
-- Name: user_custom_schema_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.user_custom_schema_id_seq', 1, false);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 220
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: tickets; Owner: postgres
--

SELECT pg_catalog.setval('tickets.user_id_seq', 1, true);


--
-- TOC entry 4790 (class 2606 OID 16717)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4824 (class 2606 OID 16781)
-- Name: comment comment_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.comment
    ADD CONSTRAINT comment_pkey PRIMARY KEY (id);


--
-- TOC entry 4836 (class 2606 OID 16802)
-- Name: label label_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.label
    ADD CONSTRAINT label_pkey PRIMARY KEY (id);


--
-- TOC entry 4856 (class 2606 OID 16843)
-- Name: password_reset password_reset_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.password_reset
    ADD CONSTRAINT password_reset_pkey PRIMARY KEY (id);


--
-- TOC entry 4809 (class 2606 OID 16754)
-- Name: priority priority_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.priority
    ADD CONSTRAINT priority_pkey PRIMARY KEY (id);


--
-- TOC entry 4844 (class 2606 OID 16823)
-- Name: queue queue_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.queue
    ADD CONSTRAINT queue_pkey PRIMARY KEY (id);


--
-- TOC entry 4853 (class 2606 OID 16838)
-- Name: session session_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);


--
-- TOC entry 4804 (class 2606 OID 16748)
-- Name: status status_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.status
    ADD CONSTRAINT status_pkey PRIMARY KEY (id);


--
-- TOC entry 4850 (class 2606 OID 16833)
-- Name: team_has_queue team_has_queue_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.team_has_queue
    ADD CONSTRAINT team_has_queue_pkey PRIMARY KEY (team_id, queue_id);


--
-- TOC entry 4833 (class 2606 OID 16796)
-- Name: team_has_user team_has_user_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.team_has_user
    ADD CONSTRAINT team_has_user_pkey PRIMARY KEY (team_id, user_id);


--
-- TOC entry 4796 (class 2606 OID 16734)
-- Name: team team_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id);


--
-- TOC entry 4822 (class 2606 OID 16772)
-- Name: ticket_for_user ticket_for_user_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_for_user
    ADD CONSTRAINT ticket_for_user_pkey PRIMARY KEY (ticket_id, user_id);


--
-- TOC entry 4840 (class 2606 OID 16807)
-- Name: ticket_has_label ticket_has_label_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_has_label
    ADD CONSTRAINT ticket_has_label_pkey PRIMARY KEY (ticket_id, label_id);


--
-- TOC entry 4830 (class 2606 OID 16790)
-- Name: ticket_modification ticket_modification_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_modification
    ADD CONSTRAINT ticket_modification_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 16764)
-- Name: ticket ticket_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT ticket_pkey PRIMARY KEY (id);


--
-- TOC entry 4800 (class 2606 OID 16742)
-- Name: ticket_type ticket_type_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_type
    ADD CONSTRAINT ticket_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4842 (class 2606 OID 16815)
-- Name: user_custom_schema user_custom_schema_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.user_custom_schema
    ADD CONSTRAINT user_custom_schema_pkey PRIMARY KEY (id);


--
-- TOC entry 4847 (class 2606 OID 16828)
-- Name: user_has_queue user_has_queue_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.user_has_queue
    ADD CONSTRAINT user_has_queue_pkey PRIMARY KEY (user_id, queue_id);


--
-- TOC entry 4793 (class 2606 OID 16726)
-- Name: user user_pkey; Type: CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- TOC entry 4825 (class 1259 OID 16863)
-- Name: fk_comment_comment1_idx15; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_comment_comment1_idx15 ON tickets.comment USING btree (parent_comment_id);


--
-- TOC entry 4826 (class 1259 OID 16862)
-- Name: fk_comment_ticket1_idx14; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_comment_ticket1_idx14 ON tickets.comment USING btree (ticket_id);


--
-- TOC entry 4834 (class 1259 OID 16868)
-- Name: fk_label_team1_idx19; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_label_team1_idx19 ON tickets.label USING btree (team_id);


--
-- TOC entry 4797 (class 1259 OID 16847)
-- Name: fk_label_team1_idx2; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_label_team1_idx2 ON tickets.ticket_type USING btree (team_id);


--
-- TOC entry 4801 (class 1259 OID 16849)
-- Name: fk_label_team1_idx3; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_label_team1_idx3 ON tickets.status USING btree (team_id);


--
-- TOC entry 4805 (class 1259 OID 16851)
-- Name: fk_label_team1_idx4; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_label_team1_idx4 ON tickets.priority USING btree (team_id);


--
-- TOC entry 4854 (class 1259 OID 16873)
-- Name: fk_password_reset_auth_user1_idx24; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_password_reset_auth_user1_idx24 ON tickets.password_reset USING btree (auth_user_id);


--
-- TOC entry 4851 (class 1259 OID 16872)
-- Name: fk_session_user1_idx23; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_session_user1_idx23 ON tickets.session USING btree (user_id);


--
-- TOC entry 4819 (class 1259 OID 16861)
-- Name: fk_table1_ticket1_idx13; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_table1_ticket1_idx13 ON tickets.ticket_for_user USING btree (ticket_id);


--
-- TOC entry 4810 (class 1259 OID 16854)
-- Name: fk_table1_user1_idx6; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_table1_user1_idx6 ON tickets.ticket USING btree (created_by_user_id);


--
-- TOC entry 4811 (class 1259 OID 16855)
-- Name: fk_table1_user2_idx7; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_table1_user2_idx7 ON tickets.ticket USING btree (modified_by_user_id);


--
-- TOC entry 4820 (class 1259 OID 16860)
-- Name: fk_table1_user3_idx12; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_table1_user3_idx12 ON tickets.ticket_for_user USING btree (user_id);


--
-- TOC entry 4812 (class 1259 OID 16853)
-- Name: fk_table1_user_idx5; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_table1_user_idx5 ON tickets.ticket USING btree (assignee_user_id);


--
-- TOC entry 4848 (class 1259 OID 16871)
-- Name: fk_team_has_queue_team1_idx22; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_team_has_queue_team1_idx22 ON tickets.team_has_queue USING btree (team_id);


--
-- TOC entry 4838 (class 1259 OID 16869)
-- Name: fk_ticket_has_label_ticket1_idx20; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_ticket_has_label_ticket1_idx20 ON tickets.ticket_has_label USING btree (ticket_id);


--
-- TOC entry 4827 (class 1259 OID 16864)
-- Name: fk_ticket_history_ticket1_idx16; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_ticket_history_ticket1_idx16 ON tickets.ticket_modification USING btree (ticket_id);


--
-- TOC entry 4828 (class 1259 OID 16865)
-- Name: fk_ticket_history_user4_idx17; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_ticket_history_user4_idx17 ON tickets.ticket_modification USING btree (modified_by_user_id);


--
-- TOC entry 4813 (class 1259 OID 16859)
-- Name: fk_ticket_priority1_idx11; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_ticket_priority1_idx11 ON tickets.ticket USING btree (priority_id);


--
-- TOC entry 4814 (class 1259 OID 16858)
-- Name: fk_ticket_status1_idx10; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_ticket_status1_idx10 ON tickets.ticket USING btree (status_id);


--
-- TOC entry 4815 (class 1259 OID 16857)
-- Name: fk_ticket_ticket_type1_idx9; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_ticket_ticket_type1_idx9 ON tickets.ticket USING btree (ticket_type_id);


--
-- TOC entry 4816 (class 1259 OID 16856)
-- Name: fk_ticket_user1_idx8; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_ticket_user1_idx8 ON tickets.ticket USING btree (customer_user_id);


--
-- TOC entry 4791 (class 1259 OID 16844)
-- Name: fk_user_auth_user1_idx1; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_user_auth_user1_idx1 ON tickets."user" USING btree (auth_user_id);


--
-- TOC entry 4845 (class 1259 OID 16870)
-- Name: fk_user_has_queue_queue1_idx21; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_user_has_queue_queue1_idx21 ON tickets.user_has_queue USING btree (queue_id);


--
-- TOC entry 4831 (class 1259 OID 16866)
-- Name: fk_user_in_team_team1_idx18; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE INDEX fk_user_in_team_team1_idx18 ON tickets.team_has_user USING btree (team_id);


--
-- TOC entry 4794 (class 1259 OID 16845)
-- Name: name_UNIQUE1; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE UNIQUE INDEX "name_UNIQUE1" ON tickets.team USING btree (name);


--
-- TOC entry 4798 (class 1259 OID 16846)
-- Name: name_UNIQUE2; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE UNIQUE INDEX "name_UNIQUE2" ON tickets.ticket_type USING btree (name);


--
-- TOC entry 4802 (class 1259 OID 16848)
-- Name: name_UNIQUE3; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE UNIQUE INDEX "name_UNIQUE3" ON tickets.status USING btree (name);


--
-- TOC entry 4806 (class 1259 OID 16850)
-- Name: name_UNIQUE4; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE UNIQUE INDEX "name_UNIQUE4" ON tickets.priority USING btree (name);


--
-- TOC entry 4837 (class 1259 OID 16867)
-- Name: name_UNIQUE6; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE UNIQUE INDEX "name_UNIQUE6" ON tickets.label USING btree (name);


--
-- TOC entry 4807 (class 1259 OID 16852)
-- Name: order_UNIQUE5; Type: INDEX; Schema: tickets; Owner: postgres
--

CREATE UNIQUE INDEX "order_UNIQUE5" ON tickets.priority USING btree ("order");


--
-- TOC entry 4870 (class 2606 OID 16944)
-- Name: comment fk_comment_comment1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.comment
    ADD CONSTRAINT fk_comment_comment1 FOREIGN KEY (parent_comment_id) REFERENCES tickets.comment(id);


--
-- TOC entry 4871 (class 2606 OID 16939)
-- Name: comment fk_comment_ticket1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.comment
    ADD CONSTRAINT fk_comment_ticket1 FOREIGN KEY (ticket_id) REFERENCES tickets.ticket(id);


--
-- TOC entry 4876 (class 2606 OID 16969)
-- Name: label fk_label_team1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.label
    ADD CONSTRAINT fk_label_team1 FOREIGN KEY (team_id) REFERENCES tickets.team(id);


--
-- TOC entry 4859 (class 2606 OID 16884)
-- Name: status fk_label_team10; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.status
    ADD CONSTRAINT fk_label_team10 FOREIGN KEY (team_id) REFERENCES tickets.team(id);


--
-- TOC entry 4858 (class 2606 OID 16879)
-- Name: ticket_type fk_label_team100; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_type
    ADD CONSTRAINT fk_label_team100 FOREIGN KEY (team_id) REFERENCES tickets.team(id);


--
-- TOC entry 4860 (class 2606 OID 16889)
-- Name: priority fk_label_team11; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.priority
    ADD CONSTRAINT fk_label_team11 FOREIGN KEY (team_id) REFERENCES tickets.team(id);


--
-- TOC entry 4884 (class 2606 OID 17009)
-- Name: password_reset fk_password_reset_auth_user1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.password_reset
    ADD CONSTRAINT fk_password_reset_auth_user1 FOREIGN KEY (auth_user_id) REFERENCES tickets.auth_user(id);


--
-- TOC entry 4883 (class 2606 OID 17004)
-- Name: session fk_session_user1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.session
    ADD CONSTRAINT fk_session_user1 FOREIGN KEY (user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4868 (class 2606 OID 16934)
-- Name: ticket_for_user fk_table1_ticket1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_for_user
    ADD CONSTRAINT fk_table1_ticket1 FOREIGN KEY (ticket_id) REFERENCES tickets.ticket(id);


--
-- TOC entry 4861 (class 2606 OID 16894)
-- Name: ticket fk_table1_user; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT fk_table1_user FOREIGN KEY (assignee_user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4862 (class 2606 OID 16899)
-- Name: ticket fk_table1_user1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT fk_table1_user1 FOREIGN KEY (created_by_user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4863 (class 2606 OID 16904)
-- Name: ticket fk_table1_user2; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT fk_table1_user2 FOREIGN KEY (modified_by_user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4869 (class 2606 OID 16929)
-- Name: ticket_for_user fk_table1_user3; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_for_user
    ADD CONSTRAINT fk_table1_user3 FOREIGN KEY (user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4881 (class 2606 OID 16994)
-- Name: team_has_queue fk_team_has_queue_queue1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.team_has_queue
    ADD CONSTRAINT fk_team_has_queue_queue1 FOREIGN KEY (queue_id) REFERENCES tickets.queue(id);


--
-- TOC entry 4882 (class 2606 OID 16999)
-- Name: team_has_queue fk_team_has_queue_team1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.team_has_queue
    ADD CONSTRAINT fk_team_has_queue_team1 FOREIGN KEY (team_id) REFERENCES tickets.team(id);


--
-- TOC entry 4877 (class 2606 OID 16974)
-- Name: ticket_has_label fk_ticket_has_label_label1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_has_label
    ADD CONSTRAINT fk_ticket_has_label_label1 FOREIGN KEY (label_id) REFERENCES tickets.label(id);


--
-- TOC entry 4878 (class 2606 OID 16979)
-- Name: ticket_has_label fk_ticket_has_label_ticket1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_has_label
    ADD CONSTRAINT fk_ticket_has_label_ticket1 FOREIGN KEY (ticket_id) REFERENCES tickets.ticket(id);


--
-- TOC entry 4872 (class 2606 OID 16949)
-- Name: ticket_modification fk_ticket_history_ticket1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_modification
    ADD CONSTRAINT fk_ticket_history_ticket1 FOREIGN KEY (ticket_id) REFERENCES tickets.ticket(id);


--
-- TOC entry 4873 (class 2606 OID 16954)
-- Name: ticket_modification fk_ticket_history_user4; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket_modification
    ADD CONSTRAINT fk_ticket_history_user4 FOREIGN KEY (modified_by_user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4864 (class 2606 OID 16924)
-- Name: ticket fk_ticket_priority1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT fk_ticket_priority1 FOREIGN KEY (priority_id) REFERENCES tickets.priority(id);


--
-- TOC entry 4865 (class 2606 OID 16919)
-- Name: ticket fk_ticket_status1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT fk_ticket_status1 FOREIGN KEY (status_id) REFERENCES tickets.status(id);


--
-- TOC entry 4866 (class 2606 OID 16914)
-- Name: ticket fk_ticket_ticket_type1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT fk_ticket_ticket_type1 FOREIGN KEY (ticket_type_id) REFERENCES tickets.ticket_type(id);


--
-- TOC entry 4867 (class 2606 OID 16909)
-- Name: ticket fk_ticket_user1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.ticket
    ADD CONSTRAINT fk_ticket_user1 FOREIGN KEY (customer_user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4857 (class 2606 OID 16874)
-- Name: user fk_user_auth_user1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets."user"
    ADD CONSTRAINT fk_user_auth_user1 FOREIGN KEY (auth_user_id) REFERENCES tickets.auth_user(id);


--
-- TOC entry 4879 (class 2606 OID 16989)
-- Name: user_has_queue fk_user_has_queue_queue1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.user_has_queue
    ADD CONSTRAINT fk_user_has_queue_queue1 FOREIGN KEY (queue_id) REFERENCES tickets.queue(id);


--
-- TOC entry 4880 (class 2606 OID 16984)
-- Name: user_has_queue fk_user_has_queue_user1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.user_has_queue
    ADD CONSTRAINT fk_user_has_queue_user1 FOREIGN KEY (user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 4874 (class 2606 OID 16964)
-- Name: team_has_user fk_user_in_team_team1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.team_has_user
    ADD CONSTRAINT fk_user_in_team_team1 FOREIGN KEY (team_id) REFERENCES tickets.team(id);


--
-- TOC entry 4875 (class 2606 OID 16959)
-- Name: team_has_user fk_user_in_team_user1; Type: FK CONSTRAINT; Schema: tickets; Owner: postgres
--

ALTER TABLE ONLY tickets.team_has_user
    ADD CONSTRAINT fk_user_in_team_user1 FOREIGN KEY (user_id) REFERENCES tickets."user"(id);


--
-- TOC entry 5066 (class 0 OID 0)
-- Dependencies: 219
-- Name: TABLE auth_user; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.auth_user TO PUBLIC;


--
-- TOC entry 5067 (class 0 OID 0)
-- Dependencies: 234
-- Name: TABLE comment; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.comment TO PUBLIC;


--
-- TOC entry 5068 (class 0 OID 0)
-- Dependencies: 239
-- Name: TABLE label; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.label TO PUBLIC;


--
-- TOC entry 5069 (class 0 OID 0)
-- Dependencies: 248
-- Name: TABLE password_reset; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.password_reset TO PUBLIC;


--
-- TOC entry 5070 (class 0 OID 0)
-- Dependencies: 229
-- Name: TABLE priority; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.priority TO PUBLIC;


--
-- TOC entry 5071 (class 0 OID 0)
-- Dependencies: 244
-- Name: TABLE queue; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.queue TO PUBLIC;


--
-- TOC entry 5072 (class 0 OID 0)
-- Dependencies: 247
-- Name: TABLE session; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.session TO PUBLIC;


--
-- TOC entry 5073 (class 0 OID 0)
-- Dependencies: 227
-- Name: TABLE status; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.status TO PUBLIC;


--
-- TOC entry 5074 (class 0 OID 0)
-- Dependencies: 223
-- Name: TABLE team; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.team TO PUBLIC;


--
-- TOC entry 5075 (class 0 OID 0)
-- Dependencies: 246
-- Name: TABLE team_has_queue; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.team_has_queue TO PUBLIC;


--
-- TOC entry 5076 (class 0 OID 0)
-- Dependencies: 237
-- Name: TABLE team_has_user; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.team_has_user TO PUBLIC;


--
-- TOC entry 5077 (class 0 OID 0)
-- Dependencies: 231
-- Name: TABLE ticket; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.ticket TO PUBLIC;


--
-- TOC entry 5078 (class 0 OID 0)
-- Dependencies: 232
-- Name: TABLE ticket_for_user; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.ticket_for_user TO PUBLIC;


--
-- TOC entry 5079 (class 0 OID 0)
-- Dependencies: 240
-- Name: TABLE ticket_has_label; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.ticket_has_label TO PUBLIC;


--
-- TOC entry 5080 (class 0 OID 0)
-- Dependencies: 236
-- Name: TABLE ticket_modification; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.ticket_modification TO PUBLIC;


--
-- TOC entry 5081 (class 0 OID 0)
-- Dependencies: 225
-- Name: TABLE ticket_type; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.ticket_type TO PUBLIC;


--
-- TOC entry 5082 (class 0 OID 0)
-- Dependencies: 221
-- Name: TABLE "user"; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets."user" TO PUBLIC;


--
-- TOC entry 5083 (class 0 OID 0)
-- Dependencies: 242
-- Name: TABLE user_custom_schema; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.user_custom_schema TO PUBLIC;


--
-- TOC entry 5084 (class 0 OID 0)
-- Dependencies: 245
-- Name: TABLE user_has_queue; Type: ACL; Schema: tickets; Owner: postgres
--

GRANT ALL ON TABLE tickets.user_has_queue TO PUBLIC;


--
-- TOC entry 2128 (class 826 OID 16390)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: tickets; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA tickets GRANT ALL ON TABLES TO PUBLIC;